from tools import safe

safe(oops)   # This will catch MyError and print traceback
